### ISSUE TITLE
V1基本功能已完成

### ISSUE THREAD

**Issue by JiehuiSun** [JiehuiSun/DataTools#16]
V1基本功能已完成

接下来就是基于V1的功能上去优化了～

V2预计过完年开始
V2预计内容有：
    1. Admin后台/前台设置登陆校验；
    2. sql联想/前台美化；
    3. 将Logo等个人的东西配置化；
    4. Sql执行/连接优化；
    

V3时间点待定
V3预计内容有：
    1. 设置人性化(提前录入可导出的字段信息, 业务人员等自行查找字段配置导出/执行的格式内容等)；
    2. 基于人性化设置做更高级的人性化，由业务人员等利用鼠标拖拽的方式去配置导出内容；
    3. 一键生产任务；
    4. 以定制化思路做配置扩展；

**Comment by JiehuiSun** [comment]
V2.1/V2.2/V2.4都已完成～

**Comment by JiehuiSun** [comment]
好吧，太忙了，暂时不更新了

**Comment by baiyibing** [comment]
谢谢你，准备试试

**Comment by JiehuiSun** [comment]
您好，邮件已收到。
